### PR TITLE
Read corrupt dfs files

### PR DESCRIPTION
**Pull request by ecomodeller**
Reading a corrupt timestep apparently messes up some internals.

A possible solution could be to close the dfs object and re-open it.

Not sure how to QA this PR☹️ But at least it should it not break any existing functionality.

### CODE REVIEW

**Comment by ecomodeller** [comment]
image

**Comment by ecomodeller** [comment]
image
Gaps seems plausible.

**Comment by ecomodeller** [comment]
Default behaviour is to raise error on bad data. Opt in to ignore bad data and the ability to choose a value to fill gaps (default missing value)
image

**Comment by ecomodeller** [comment]
fill_corrupt

**Review by jsmariegaard — APPROVED** [review]
I think it would be best to have the same functionality for dfs123, but I guess that can come later. 
It would be good to add the new arguments to `__init__.py/read()` docstring. Ideally, a small example in `interp_na()` docstring would be nice. Otherwise good.

**Pull request merged**
