### PR TITLE
dfsu plot: non-equidistant levels and extend

### PR DESCRIPTION
**Pull request by jsmariegaard**
Addresses #193

### CODE REVIEW

**Comment by jsmariegaard** [comment]
@jouArc could you please try this?

**Comment by jsmariegaard** [comment]
You can test this branch by upgrading mikeio:

     > pip install –upgrade https://github.com/DHI/mikeio/archive/dfsu_colorbar.zip

**Comment by jsmariegaard** [comment]
Try this branch with:

    > pip install –upgrade https://github.com/DHI/mikeio/archive/dfsu_colorbar.zip

**Comment by jouArc** [comment]
It works perfectly fine !
Thanks !!  :)

**Comment by ecomodeller** [comment]
Merged into `main`

**Pull request closed without merging**
