### PR TITLE
Faster dfs{2,3} write

### PR DESCRIPTION
**Pull request by ecomodeller**
Before:
image

After:
image

### CODE REVIEW

**Comment by ecomodeller** [comment]
Thanks to @PierreBrinkSwiegers for pointing out this flaw 👏

**Review by jsmariegaard — CHANGES_REQUESTED** [review]
Could you please fix for dfs3 as well https://github.com/DHI/mikeio/blob/5a9427168b39efab5c96de8ccff9b7b87f444932/mikeio/dfs3.py#L114 ?

**Comment by ecomodeller** [comment]
> Could you please fix for dfs3 as well
> 
> https://github.com/DHI/mikeio/blob/5a9427168b39efab5c96de8ccff9b7b87f444932/mikeio/dfs3.py#L114
> 
> ?

Hmm, looks like somebody has been copy/pasting their way to productivity instead of writing clean code. Who could it be?

```console
$ git blame mikeio/dfs3.py|grep "def _write_dfs3_data"
5b98457a mikeio/dfs3.py (Henrik Andersson          2022-04-20 09:35:07 +0200  97) def _write_dfs3_data(dfs: DfsFile, ds: Dataset) -> None:
```

Time for some light refactoring :see_no_evil:

**Comment by jsmariegaard** [comment]
I was also wondering if this is the best way to find if a DatetimeIndex is equidistant: 

    return len(self.time.to_series().diff().dropna().unique()) == 1 

? 

And/or whether we should cache this?

**Comment by ecomodeller** [comment]
> I was also wondering if this is the best way to find if a DatetimeIndex is equidistant:
> 
> ```
> return len(self.time.to_series().diff().dropna().unique()) == 1 
> ```
> 
> ?
> 
> And/or whether we should cache this?

It should be safe to cache this, the time axis should be immutable.

**Pull request merged**
