### PR TITLE
Exporting Dfsu to Dfs2

### PR DESCRIPTION
**Pull request by georgebv**
This PR introduces a new method to the `Dfsu` class - `.to_dfs2`. This method provides an interface to convert `Dfsu` to `Dfs2` with similar functionality to what DHI MIKE has when creating DFS2 files from DFSU files.

### CODE REVIEW

**Comment by georgebv** [comment]
@ecomodeller @jsmariegaard I cloned the repo and, before making any changes, I used `black` to format the `mikeio/dfsu.py` file, as specified in your contributing guidelines. As you can see, `black` formats the current `dfsu` file - are you OK with this?

I use black all the time on other projects and all the formats made were totally expected. I am just not sure whether this commit won't interfere with other branches you work on.

**Comment by georgebv** [comment]
I was working on #155 and realized that in order to be able to reliably create raster/2D grids the package is currently missing some key components. Namely, we need the following:

1. function/class for conversion between `projection_string` and EPSG (both directions)
2. Way to determine `Dfs2.write` orientation in the `coordinate` argument

To solve 1, I propose making `pyproj` a dependency (it has wheels on PyPI, so installation is not a problem - this should be an easy dependency). Then writing a function to convert between the two should be relatively trivial. I suggest making a class which would define a `mikeio.CRS` object and would have methods (both to- and from-, I show only to-) such as `to_projection_string` (DHI format), `to_epsg` (returns integer code), `to_pyproj`, `to_wkt` (well-known text), etc. Naturally, I cannot do this myself because this requires knowledge of DHI coordinate system nomenclature. @ecomodeller , @jsmariegaard - can you help with this? I can help you create the Class if you tell me how DHI CRS's work.

I found a way to solve 2 when working on DFSU/DFS2 objects for our firm (COWI) internal Python library using MIKE SDK. This solution, however, requires 1 to be solved first (in our library we used a function to convert from UTM string in MIKE to pyproj, non-utm coordinate systems were rejected via ValueError).

**Comment by jsmariegaard** [comment]
Hi @georgebv - have you seen https://github.com/DHI/mikeio/blob/master/notebooks/Dfsu%20-%202D%20interpolation.ipynb which shows how to interpolate a dfsu to an overset grid and to export to dfs2. Doesn't this cover most of it?

**Comment by georgebv** [comment]
@jsmariegaard it doesn't cover grid rotation and CRS, which would be required for raster export - these two features are incompatible with `Grid2D`, which is strictly flat and uses internal DHI notation for coordinate systems. It may be a good idea to update `Grid2D` class to add rotation (orientation) to it. New `CRS` class is required too. Please see my points above

**Comment by jsmariegaard** [comment]
> @ecomodeller @jsmariegaard I cloned the repo and, before making any changes, I used `black` to format the `mikeio/dfsu.py` file, as specified in your contributing guidelines. As you can see, `black` formats the current `dfsu` file - are you OK with this?
> 
> I use black all the time on other projects and all the formats made were totally expected. I am just not sure whether this commit won't interfere with other branches you work on.

Yes, we use black too - but it's probably something with different versions???

**Comment by georgebv** [comment]
I use the latest version, you don't specify version in your contribution guidelines.

**Comment by jsmariegaard** [comment]
> I use the latest version, you don't specify version in your contribution guidelines.

Sure. That's fine. I am not sure if that is the problem at all. I just noticed this in other situations as well.

**Comment by jsmariegaard** [comment]
I've been thinking more on what you wrote on orientation and CRS. I think it's a good idea with some sort of projection class - but I am not the best person to advise on CRS. But as a start, I can provide a few relevant links: 

* https://manuals.mikepoweredbydhi.help/2021/General/MIKE_Zero_Geodesy.pdf 
* https://manuals.mikepoweredbydhi.help/2021/General/Class_Library/DHI_Projections/html/N_DHI_Projections.htm 

The latter is documentation for the Projections assembly which is in the bin folder of mikeio. In here you will also find the Cartography class which is used in the Dfs2 class already https://github.com/DHI/mikeio/blob/ca7f3e6ce73c9e216c99a76c3d813f88a7442e30/mikeio/dfs2.py#L91 

I am not sure, though, why we could not start with to_dfs2() method that just outputs the dfs2 in the same projection as the dfsu and without any rotation and using the overset grid? That would make a good small PR before moving on to the next thing...

**Comment by georgebv** [comment]
> I am not sure, though, why we could not start with to_dfs2() method that just outputs the dfs2 in the same projection as the dfsu and without any rotation and using the overset grid? That would make a good small PR before moving on to the next thing...

Good point. I can raise `NotImplementedError` if epsg or rotation values are passed. Ideally this method should be fully equivalent to the functionality of MIKE itself, when you create dfs2 from dfsu. I think this will require four PR's for that:

1. dfsu to dfs2 skeleton (this PR)
2. CRS class, which translates MIKE projection_strings to common notation (epsg, wkt, etc.)
3. update dfsu to dfs2 to feature full MIKE-compliant workflow (rotation and epsg)
4. dfs2 to raster method

I will try to finish the first one this week. As for number 2, I have some ideas, but it will be a team effort as, in the long run, it may be used by all dfs* classes.

**Comment by georgebv** [comment]
@jsmariegaard I think the PR is ready. I added both method and tests. I also creates `conftest.py` to dynamically dispatch fixtures for it as well. Changes in areas of code outside of functions I created are due to `black` - it appears that either older version of black was used for those sections or they were not formatted.

Let me know if this works. I suggest several next steps, those are listed in my previous comment.

**Comment by ecomodeller** [comment]
Merged

**Pull request merged**
