### PR TITLE
DataArray argmin/argmax

### PR DESCRIPTION
**Pull request by jsmariegaard**
To find the index of min/max values

### CODE REVIEW

**Comment by ecomodeller** [comment]
More to add here or :shipit: ?

**Comment by jsmariegaard** [comment]
> More to add here or :shipit: ?

I don't have more to add here. What do you think?

**Comment by ecomodeller** [comment]
> > More to add here or :shipit: ?
> 
> I don't have more to add here. What do you think?

That I don't like failing tests...

The quick test running on Python 3.9 works fine, but the test on 3.7 fails 😢 

The last version of NumPy for 3.7 is 1.21.6 released Apr 12, 2022

**Comment by jsmariegaard** [comment]
Apparently, not ready after all as it does not work on py3.7. Further development on hold for a few weeks.

**Comment by jsmariegaard** [comment]
Will close this as the need is not obvious.

**Pull request closed without merging**
