### PR TITLE
Added download button

### PR DESCRIPTION
**Pull request by daniel-caichac-DHI**
on readme.md

Quite straight forward

### CODE REVIEW

**Comment by jsmariegaard** [comment]
I think @ecomodeller should take the decision on this one.

**Comment by ecomodeller** [comment]
It is a small badge next to the other badges, but to whom does the information add value?

The metric can only be seen in relation to other packages, the actual number is not that useful since most downloads are from automated processes like CI and docker builds.

**Comment by ecomodeller** [comment]
Numpy has download stats on their readme.

**Review by ecomodeller — APPROVED** [review]

**Comment by daniel-caichac-DHI** [comment]
Well I did not have a chance to answer but yeah numpy and others.
I think it can give you a relative number of how many people/bots are downloading it, also compared to another libraries (modelskill, watobs) and maybe hint towards where to add more resources/efforts, even if the numbers are pumped by some bots.
Just saying

**Pull request merged**
