### PR TITLE
Adding snow compare example

### PR DESCRIPTION
**Pull request by dykdhi**
Adding a new notebook and some example data. I'm not familiar with quarto so let me know if there are any issues with the PR.

### CODE REVIEW

**Comment by ecomodeller** [comment]
@dykdhi how about we put this notebook in the notebooks folder for now https://github.com/DHI/mikeio/tree/main/notebooks
And think about it for a while if it makes sense to have it in the docs/examples.

**Comment by dykdhi** [comment]
@ecomodeller Ok, I'll make this update

**Comment by dykdhi** [comment]
Revert went wrong, will make a new PR

**Comment by dykdhi** [comment]
.

**Pull request closed without merging**
