### PR TITLE
Prepare for python 3.13

### PR DESCRIPTION
**Pull request by ryan-kipawa**

### CODE REVIEW

**Comment by ryan-kipawa** [comment]
From testing locally, there's one issue with our optional dependency netcdf4 (dev/notebooks):

https://github.com/Unidata/netcdf4-python/issues/1365

Maybe it will be resolved soon. Otherwise the core dependencies seem fine for 3.13 😄

**Comment by jsmariegaard** [comment]
Great, thanks @ryan-kipawa !

**Comment by ecomodeller** [comment]
Github has not picked up https://www.python.org/downloads/release/python-3130/ yet.

**Comment by ecomodeller** [comment]
Not sure if Snyk is parsing the `pyproject.toml` , seems like it is only looking at `requirements_min.txt`🤔
image
image

**Review by ryan-kipawa — COMMENTED** [review]
Looks good to me 🚀 ... GitHub won't let me approve since I authored the PR

**Review by jsmariegaard — APPROVED** [review]
:shipit:

**Pull request merged**
