### PR TITLE
Parse MIKE SHE Pfs

### PR DESCRIPTION
**Pull request by ecomodeller**

### CODE REVIEW

**Comment by ecomodeller** [comment]
@jsmariegaard The parsing error occurs inside the `parse_yaml_preserving_duplicate`, but it seems it can be parsed with the normal loader, should this be the default strategy to try first instead of last, I can't really tell when to use which loader.

**Comment by jsmariegaard** [comment]
@ecomodeller, please see my analysis in https://github.com/DHI/mikeio/issues/463

**Comment by jsmariegaard** [comment]
Furthermore, it would be nice if the parse could provide some feedback on where in the file it failed...

**Comment by jsmariegaard** [comment]
@ecomodeller, note that I changed the default to NOT insist on unique keywords/section names. This may not be ideal for MIKE FM type of models but as we have seen for MIKE SHE and other engines this is the standard. We could have `None` as the default value and then have a list of file extensions to dynamically set the default behavior, but I don't know... what do you think?

**Comment by jsmariegaard** [comment]
Also, the implementation is now (after handling combinations of non-unique keywords and sections) less elegant as can be seen from the diff, so ideas on improving is very welcome.

**Comment by jsmariegaard** [comment]
And... I am not sure if we really need the long complete MIKE SHE file, now that we have the smaller condensed one?

**Comment by ecomodeller** [comment]
> And... I am not sure if we really need the long complete MIKE SHE file, now that we have the smaller condensed one? 

Probably not.

**Comment by ecomodeller** [comment]
@watermain can you test if this branch works with some of your MIKE SHE examples?

The branch can be installed like this:
```console
$ pip install https://github.com/DHI//mikeio/archive/pfs_she.zip
```

**Comment by watermain** [comment]
Hi @ecomodeller, I think there must be an installation issue: The problems persists after updating as suggested. Any ideas?

**Comment by ecomodeller** [comment]
I guess you have to add --upgrade --force-reinstall, since you already have mikeio installed.

**Comment by watermain** [comment]
Ok cool, reading seems to work now! Writing however fails - generally, it seems, so I´m not adding a sample she file, but let me know if you need more details!

**Comment by jsmariegaard** [comment]
> Ok cool, reading seems to work now! Writing however fails - generally, it seems, so I´m not adding a sample she file, but let me know if you need more details!

@watermain , could you please provide a minimal failing test to this PR?

**Comment by watermain** [comment]
With the latest commit read/write of she files works in almost all cases. I have run tests on many old support cases, and there are a few remaining special cases: Apostrophes in filenames don´t work, like this one:
FILE_NAME = |.\Inputs\11_Storing of results\ouvrages\Pont de l'Angle 1h.dfs0|
Strings that could almost be parsed as floats, but should still be just handled as strings, like this:
ItemDescr = 'E-1'
(or 'E12'...)
Then there is one file where it does not say which pfs line makes it fail, so I added the whole file DK4_100m_2020_Ribe_Submodel_flood_run-70ems3b.she to test data, it´s a bit large though, so feel free to discard it before merging. I added the previous 2 cases to this file, so the first 2 issues may need to be fixed to see the 3rd issue.
I also included other pfs types in the test, and there may be more issues, but I´ll leave it at this for now.

**Comment by ecomodeller** [comment]
Writing non-unique keywords fails in this branch, but works in main. The scientific approach to finding where the regression was introduced is bisection using [`git bisect`](https://git-scm.com/docs/git-bisect)

This is the result:
```console
759a4cc580cdcf80f66635fcc8f939d3ae71a395 is the first bad commit
commit 759a4cc580cdcf80f66635fcc8f939d3ae71a395
Author: Jesper Sandvig Mariegaard <34088801+jsmariegaard@users.noreply.github.com>
Date:   Thu Nov 3 16:08:47 2022 +0100

    handle non-unique mix of keywords and sections

 mikeio/pfs.py     | 24 ++++++++++++++++++------
 tests/test_pfs.py |  2 +-
 2 files changed, 19 insertions(+), 7 deletions(-)
```

**Comment by jsmariegaard** [comment]
@watermain I fixed all known issues. Could you please confirm that it now works? 

It should be noted, though, that certain combinations of characters in strings can still confuse it, e.g.: 

     E = |str,s'+-s_d.dfs0|

See the disabled lines in test_difficult_chars_in_str().  https://github.com/DHI/mikeio/blob/97f4149e7bd43e68e3932aacfc0055f1c6b62846/tests/test_pfs.py#L602 

@ecomodeller or @watermain could one of you please review the PR a final time? I think we should then merge.

**Comment by jsmariegaard** [comment]
Thanks @watermain, it's clear that we need better parsing of parameters. Maybe we should use csv or shlex module to split the strings in tokens.

**Comment by jsmariegaard** [comment]
@watermain and @ecomodeller - I think we should merge this PR now even though a few issues remain unsolved. I would propose creating those as issues and then opening a new PR. @ecomodeller also suggested having an option to allow loading a pfs file in text mode which could be a fallback strategy if the normal parsing fails.

**Comment by jsmariegaard** [comment]
closes #470

**Comment by jsmariegaard** [comment]
All known issues have been fixed except strings that could also be a valid scientific float representation e.g. 

    ID_A = '1E-3'

We will need to make this an issue and work on it in another PR.

**Review by ecomodeller — COMMENTED** [review]
The test coverage for pfs.py is 87 %

Most lines missing tests are not created in this PR. But it would still be good to know if the untested lines are actually used.

For example this method:
image

**Pull request merged**
