### PR TITLE
Option to hide progress bars

### PR DESCRIPTION
**Pull request by ecomodeller**

### CODE REVIEW

**Review by mohm-dhi — APPROVED** [review]
It looks very good. I rather prefer to have the default as True.

Thanks.

**Comment by jsmariegaard** [comment]
Would it make sense to:

a) call the option show_progress (instead of hide_progress)? 
b) make the default conditional on the file size: enable for large files? (then most users don't need to worry about show/hide)

**Comment by mohm-dhi** [comment]
Looks great to me. Thanks

> Would it make sense to:
> 
> a) call the option show_progress (instead of hide_progress)?
> b) make the default conditional on the file size: enable for large files? (then most users don't need to worry about show/hide)

a) I like to have show_progress and default as False. 
b) It is not just about file size, sometimes user want to read items in a loop which which end up to have lots of progress bar.

**Comment by mohm-dhi** [comment]
Hi @ecomodeller,
Could you please merge this? Thank you!

**Pull request merged**
