### PR TITLE
New MIKE dlls v19.0.0

### PR DESCRIPTION
**Pull request by rhaDHI**
From NuGet packages DHI.Mike1D.ResultDataAccess (includes dfs and eum) and DHI.Mike1D.CrossSectionModule (for PFS).

### CODE REVIEW

**Comment by jsmariegaard** [comment]
The Gold version should be ready (at least the installers are since last week). So why use RC2?

**Comment by rhaDHI** [comment]
There was a lot of unneeded files and I was cleaning them up anyway trying to solve https://github.com/DHI/mikeio/issues/138 . But let's update this PR with the actual release files. Didn't know they were that close 👍

**Comment by jsmariegaard** [comment]
The release is out https://www.mikepoweredbydhi.com/mike-2021

**Comment by ecomodeller** [comment]
> There was a lot of unneeded files and I was cleaning them up anyway trying to solve #138 . But let's update this PR with the actual release files. Didn't know they were that close 👍 This was the newest on the internal nuget feed.

@rhaDHI Will you update with the final release?

**Comment by rhaDHI** [comment]
Yep. The release is also on public nuget now. The public nuget dll's v19.0.0 are the exact same as the internally released 19.0.0-rc2 that included. So you can go ahead and merge.

**Pull request merged**
