### PR TITLE
First step towards html repr

### PR DESCRIPTION
**Pull request by ecomodeller**
repr

### CODE REVIEW

**Comment by jsmariegaard** [comment]
😍

**Comment by ecomodeller** [comment]
Some challenges remain, mainly that the top level `Pfs` is not a `PfsSection`
pfs_repr_html2

**Comment by jsmariegaard** [comment]
Wauw. Looks great! 

Let's make another pull request by refactoring a common class _PfsBase from Pfs and PfsSection! (or maybe simply make Pfs inherit from PfsSection)?

**Comment by ecomodeller** [comment]
This PR will be revived once #487 has been completed.

**Comment by jsmariegaard** [comment]
> This PR will be revived once #487 has been completed.

Are you trying to stress me 😛 ?

**Comment by ecomodeller** [comment]
No, note to self

**Comment by ecomodeller** [comment]
TODO: handle aliases
image

**Comment by ecomodeller** [comment]
It works great in VS Code, but in Jupyter Lab/Notebook the css is not interpreted in the same way for some reasone
image

The list bullets should be hidden by this:☹️
```css
ul {list-style-type: none; }
```

**Comment by ecomodeller** [comment]
<details>
<summary>summary/details html</summary>
Seems like a better structure than using CSS🤔
https://www.w3schools.com/tags/tag_summary.asp
</details>

**Comment by ecomodeller** [comment]
Interesting, but for now we stick to a simple text.

**Pull request closed without merging**
