### PR TITLE
Add extract_timesteps

### PR DESCRIPTION
**Pull request by jsmariegaard**
Add new generic dfs0 method that can extract timesteps within a range from any dfs file and output to new dfs file

### CODE REVIEW

**Comment by jsmariegaard** [comment]
I am not sure about the best name for this method? 

* subset_time()
* select_time()
* timesteps_to_file()
* time_range_to_file()
* extract_timesteps()

?

**Comment by ecomodeller** [comment]
I think `extract_timesteps` is fine. I can also imagine an `extract` that creates a subset both in items and timesteps. Subsetting in space is a bit more difficult to handle in this generic module.

**Comment by jsmariegaard** [comment]
Note: relative time axis not supported!

It would be nice to add a **stride** and/or **dt** argument for equidistant calendar files.

**Review by ecomodeller — APPROVED** [review]
:shipit:

**Comment by jsmariegaard** [comment]
@ecomodeller, can you merge this PR? I am not authorized.

**Pull request merged**
