### PR TITLE
add time property to mikeio.open and add test

### PR DESCRIPTION
**Pull request by mohm-dhi**
It was often that we only need all the datetimes in the file without reading the entire file or any item. I just add that property

### CODE REVIEW

**Comment by jsmariegaard** [comment]
Great idea - I have thinking about the same. We just need it on dfs0, 1, 2, and 3 also for consistency. At least in dfs0, we should handle non-equidistant time axis also.

**Comment by mohm-dhi** [comment]
@jsmariegaard I am sorry, I was very busy that could not work on this. I hope to find some time next week to make the necessary changes.

**Comment by jsmariegaard** [comment]
Great. No rush.

**Comment by mohm-dhi** [comment]
> pd.DatetimeIndex

output datetimes are in pd.DatetimeIndex, I added an assert to check for that too.

**Comment by mohm-dhi** [comment]
> Great idea - I have thinking about the same. We just need it on dfs0, 1, 2, and 3 also for consistency. At least in dfs0, we should handle non-equidistant time axis also.

I just added the time property to dfs0 equidistant and non-equidistant time axis, will do the dfs 1, 2 and 3 later

**Pull request merged**
