### PR TITLE
Interpolation matrix multiply (testing...)

### PR DESCRIPTION
**Pull request by ecomodeller**
Vector multiplication in loop replaced with matrix multiplication. (See #413)

Still left to do: create weights matrix without loop.

### CODE REVIEW

**Comment by jsmariegaard** [comment]
I think it's better just to replace the whole thing with:

    def _interp_itemstep(data, elem_ids, weights=None):
        if weights is None:
            return data[elem_ids]
        else:
            return np.sum(data[elem_ids]*weights, axis=1)

This is equivalent to taking the dot product of each row but much much faster.

**Comment by jsmariegaard** [comment]
Closer investigation shows that this is needed: 

    def _interp_itemstep(data, elem_ids, weights=None):
      if weights is None:
        return data[elem_ids]
      else:
        idat = data[elem_ids] * weights
        return np.sum(idat, axis=1) if weights.ndim == 2 else idat

To also handle the cases when n_nearest=1...

**Comment by jsmariegaard** [comment]
You closed this? But wouldn't it be good to implement my suggestion?

**Comment by ecomodeller** [comment]
Sure, I'll create a new branch with a fresh start

**Pull request closed without merging**
