### PR TITLE
dataset concatenation single timestep

### PR DESCRIPTION
**Pull request by clemenscremer**
modified dataset test to concatenate file with single timestep. When concantenating will result in error in shape check as well as dims check as time dimension is dropped for single timestep datasets and not available for checking.

### CODE REVIEW

**Comment by clemenscremer** [comment]
should we keep dimensions when selecting single timestep?
this would prevent checks during concatenation from failing

image

**Comment by ecomodeller** [comment]
> should we keep dimensions when selecting single timestep? this would prevent checks during concatenation from failing
> 
> image

I don't think so.

We changed this behaviour to v 1.0 in order to make it consistent with e.g. Xarray and also to make plotting easier.

If you select a single timestep from a dataset with 3 dimensions (time, y, x) you end up with a dataset with two dimensions (y,x).

This is also how indexing in NumPy works
```python
>>> A
array([[[0.9, 0.4, 0.6, 0.4],
        [0.5, 0.4, 0.1, 0.4],
        [0.9, 0.4, 0.3, 0.9]],

       [[0.3, 0.7, 0.4, 0.8],
        [0.7, 0.7, 0.3, 0.4],
        [0.2, 0.8, 0.9, 0.8]]])
>>> A[:,:,0]
array([[0.9, 0.5, 0.9],
       [0.3, 0.7, 0.2]])
>>> A.shape
(2, 3, 4)
>>> A[:,:,0].shape
(2, 3)
```

But concatenation should still be able to work somehow 😉

**Comment by jsmariegaard** [comment]
@clemenscremer - could you change the name of this PR to something more meaningful? Thanks

**Comment by ecomodeller** [comment]
1. Make sure it works for most (all?) sorts of data.
2. Is it consistent with `generic.concat`?
3. Release as part of v 1.2 🚀

**Review by jsmariegaard — APPROVED** [review]
Looks good. I tried hard to break with all sorts of dfs files, combinations of single and multi-timesteps for both Dataset and DataArray. But I couldn't. Well done!

**Pull request merged**
