### PR TITLE
Simplify plot map

### PR DESCRIPTION
**Pull request by ecomodeller**
Before:
`mikeio.spatial.FM_utils._plot_map()` has a [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) of 50

> ...In his presentation 'Software Quality Metrics to Identify Risk'[8] for the Department of Homeland Security, Tom McCabe introduces the following categorisation to interpret cyclomatic complexity:
> 
> 1 - 10 Simple procedure, little risk
> 11 - 20 More complex, moderate risk
> 21 - 50 Complex, high risk
> \> 50 Untestable code, very high risk
> 

Status:
complexity of 32

Improved, but still one of the most complex functions in MIKE IO.

### CODE REVIEW

**Comment by ecomodeller** [comment]
```console
$ flake8 --max-complexity 20 --select=C901 mikeio/spatial/
mikeio/spatial/FM_utils.py:12:1: C901 '_plot_map' is too complex (26)
```

**Comment by ecomodeller** [comment]
Complexity is now acceptable, have we lost any essential functionality in the process🤔
```console
flake8 --max-complexity 15 --select=C901 mikeio/spatial/
mikeio/spatial/FM_utils.py:12:1: C901 '_plot_map' is too complex (20)
```

**Review by jsmariegaard — CHANGES_REQUESTED** [review]
Generally, looks super good. I did find, though that a colorbar now appears in contour plots. Before it looked like this: 

image

Now has a colorbar: 

image

Could you please change this back (if the purpose is to only change the code and not the functionality). 

Another small comment: you have added a number of TODOs - should these be kept is it something that should be fixed before merging?

**Comment by ecomodeller** [comment]
> Generally, looks super good. I did find, though that a colorbar now appears in contour plots. Before it looked like this:
> 
> image
> 
> Now has a colorbar:
> 
> image
> 
> Could you please change this back (if the purpose is to only change the code and not the functionality).
> 
> Another small comment: you have added a number of TODOs - should these be kept is it something that should be fixed before merging?

The TODOs are left there as bookmarks for future improvers😉

**Comment by ecomodeller** [comment]
One day when we are very pleased with the output of the plotting capabilities in MIKE IO we could consider adding image comparison tests.
https://matplotlib.org/stable/devel/testing.html#writing-an-image-comparison-test

**Pull request merged**
